from .base import *


USER_RABBITMQ = env.str('USER_RABBITMQ', '')
PASSWORD_RABBITMQ = env.str('PASSWORD_RABBITMQ', '')
RABBITMQ_HOST = env.str('RABBITMQ_HOST', '')
RABBITMQ_PORT = env.int('RABBITMQ_PORT', '')
RABBITMQ_VHOST = env.str('RABBITMQ_VHOST', '')
QUEUE_RABBITMQ = env.str('QUEUE_RABBITMQ', '')
